package space.terwer;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.3.11
 * 2022-11-07T14:56:02.333+08:00
 * Generated source version: 3.3.11
 *
 */
@WebService(targetNamespace = "http://terwer.space/", name = "IWeatherService")
@XmlSeeAlso({ObjectFactory.class})
public interface IWeatherService {

    @WebMethod
    @RequestWrapper(localName = "queryWeather", targetNamespace = "http://terwer.space/", className = "space.terwer.QueryWeather")
    @ResponseWrapper(localName = "queryWeatherResponse", targetNamespace = "http://terwer.space/", className = "space.terwer.QueryWeatherResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String queryWeather(

        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );
}
